# diffusion_policy/config/task/hand_umi.yaml
name: hand_umi

# Dataset is already temporally aligned at collection time.
# Therefore we disable all latency alignment here.
camera_obs_latency: 0.0
robot_obs_latency: 0.0
gripper_obs_latency: 0.0
dataset_frequeny: 0.0
obs_down_sample_steps: 3  # keep same as umi; set to 1 if you don't want downsampling

low_dim_obs_horizon: 2
img_obs_horizon: 2
action_horizon: 16
ignore_proprioception: False

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    camera0_rgb:
      shape: [3, 224, 224]
      horizon: ${task.img_obs_horizon} # int
      latency_steps: 0 # float
      down_sample_steps: ${task.obs_down_sample_steps} # int
      type: rgb
      ignore_by_policy: False
      
    robot0_eef_pos:
      shape: [3]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      ignore_by_policy: ${task.ignore_proprioception}

    # stored in zarr as rotvec axis-angle (T,3),
    # but converted to rotation_6d (T,6) by dataset according to rotation_rep.
    robot0_eef_rot_axis_angle:
      raw_shape: [3]
      shape: [6]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      rotation_rep: rotation_6d
      ignore_by_policy: ${task.ignore_proprioception}

    # your hand keypoints: (T,75) float32
    robot0_hand_nodes:
      shape: [75]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      ignore_by_policy: ${task.ignore_proprioception}

    # pose with respect to episode start (kept for compatibility with pose_repr=relative)
    robot0_eef_rot_axis_angle_wrt_start:
      raw_shape: [3]
      shape: [6]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      ignore_by_policy: ${task.ignore_proprioception}

  action:
    shape: [84] # 3 for pos, 3 for rot, 1 for gripper width, 75 for hand keypoints
    horizon: ${task.action_horizon}
    latency_steps: 0
    down_sample_steps: ${task.obs_down_sample_steps}
    rotation_rep: rotation_6d

task_name: &task_name hand_umi

# default dataset path; you can override from CLI:
# task.dataset_path=.../dataset.zarr.zip
# dataset_path: example_demo_session/dataset.zarr.zip
dataset_path: hand_umi_dataset/dataset.zarr.zip

pose_repr: &pose_repr
  obs_pose_repr: relative     # abs or rel
  action_pose_repr: relative  # abs or rel or delta

env_runner:
  _target_: diffusion_policy.env_runner.real_pusht_image_runner.RealPushTImageRunner

dataset:
  _target_: diffusion_policy.dataset.umi_dataset.UmiDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  cache_dir: null
  pose_repr: *pose_repr
  action_padding: False
  temporally_independent_normalization: False
  repeat_frame_prob: 0.0
  max_duration: null
  seed: 42
  val_ratio: 0.05
