# diffusion_policy/config/task/inspire_bimanual.yaml
name: inspire_bimanual

# Dataset is already temporally aligned at collection time.
# Therefore we disable all latency alignment here.
camera_obs_latency: 0.0
robot_obs_latency: 0.0
gripper_obs_latency: 0.0
dataset_frequeny: 0.0
obs_down_sample_steps: 3  # keep same as umi; set to 1 if you don't want downsampling

low_dim_obs_horizon: 2
img_obs_horizon: 2
action_horizon: 16
ignore_proprioception: False

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    # -----------------------------
    # Cameras
    # -----------------------------
    camera0_rgb:
      shape: [3, 224, 224]
      horizon: ${task.img_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: rgb
      ignore_by_policy: False

    camera1_rgb:
      shape: [3, 224, 224]
      horizon: ${task.img_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: rgb
      ignore_by_policy: False

    camera2_rgb:
      shape: [3, 224, 224]
      horizon: ${task.img_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: rgb
      ignore_by_policy: False

    # -----------------------------
    # Robot0 (left arm / left hand)
    # -----------------------------
    robot0_eef_pos:
      shape: [3]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      ignore_by_policy: ${task.ignore_proprioception}

    # stored in zarr as rotvec axis-angle (T,3),
    # but converted to rotation_6d (T,6) by dataset according to rotation_rep.
    robot0_eef_rot_axis_angle:
      raw_shape: [3]
      shape: [6]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      rotation_rep: rotation_6d
      ignore_by_policy: ${task.ignore_proprioception}

    robot0_hand_angles:
      shape: [6]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      ignore_by_policy: ${task.ignore_proprioception}
  
    robot0_touch_pinky:
      shape: [93]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      ignore_by_policy: False

    robot0_touch_ring:
      shape: [93]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      ignore_by_policy: False

    robot0_touch_middle:
      shape: [93]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      ignore_by_policy: False

    robot0_touch_index:
      shape: [93]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      ignore_by_policy: False

    robot0_touch_thumb:
      shape: [105]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      ignore_by_policy: False

    robot0_touch_palm:
      shape: [56]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      ignore_by_policy: False

    # pose with respect to episode start
    robot0_eef_rot_axis_angle_wrt_start:
      raw_shape: [3]
      shape: [6]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      ignore_by_policy: ${task.ignore_proprioception}

    # robot0 with respect to robot1
    robot0_eef_pos_wrt1:
      shape: [3]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      ignore_by_policy: ${task.ignore_proprioception}

    robot0_eef_rot_axis_angle_wrt1:
      raw_shape: [3]
      shape: [6]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      ignore_by_policy: ${task.ignore_proprioception}

    # -----------------------------
    # Robot1 (right arm / right hand)
    # -----------------------------
    robot1_eef_pos:
      shape: [3]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      ignore_by_policy: ${task.ignore_proprioception}

    robot1_eef_rot_axis_angle:
      raw_shape: [3]
      shape: [6]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      rotation_rep: rotation_6d
      ignore_by_policy: ${task.ignore_proprioception}

    robot1_hand_angles:
      shape: [6]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      ignore_by_policy: ${task.ignore_proprioception}

    robot1_touch_pinky:
      shape: [93]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      ignore_by_policy: False

    robot1_touch_ring:
      shape: [93]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      ignore_by_policy: False

    robot1_touch_middle:
      shape: [93]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      ignore_by_policy: False

    robot1_touch_index:
      shape: [93]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      ignore_by_policy: False

    robot1_touch_thumb:
      shape: [105]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      ignore_by_policy: False

    robot1_touch_palm:
      shape: [56]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      ignore_by_policy: False

    # pose with respect to episode start
    robot1_eef_rot_axis_angle_wrt_start:
      raw_shape: [3]
      shape: [6]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      ignore_by_policy: ${task.ignore_proprioception}

    # robot1 with respect to robot0
    robot1_eef_pos_wrt0:
      shape: [3]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      ignore_by_policy: ${task.ignore_proprioception}

    robot1_eef_rot_axis_angle_wrt0:
      raw_shape: [3]
      shape: [6]
      horizon: ${task.low_dim_obs_horizon}
      latency_steps: 0
      down_sample_steps: ${task.obs_down_sample_steps}
      type: low_dim
      ignore_by_policy: ${task.ignore_proprioception}

  action:
    shape: [30]   # (pos3 + rot6d6 + hand6) * 2 robots
    horizon: ${task.action_horizon}
    latency_steps: 0
    down_sample_steps: ${task.obs_down_sample_steps}
    rotation_rep: rotation_6d

task_name: &task_name inspire_bimanual

# default dataset path; can be overridden from CLI
dataset_path: hand_inspire_dataset/dataset.zarr.zip

pose_repr: &pose_repr
  obs_pose_repr: relative     # abs or rel
  action_pose_repr: relative  # abs or rel or delta

env_runner:
  _target_: diffusion_policy.env_runner.real_pusht_image_runner.RealPushTImageRunner

dataset:
  _target_: diffusion_policy.dataset.umi_dataset.UmiDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  cache_dir: null
  pose_repr: *pose_repr
  action_padding: False
  temporally_independent_normalization: False
  repeat_frame_prob: 0.0
  max_duration: null
  seed: 42
  val_ratio: 0.05